### PR TITLE
added placeholder offline player support

### PR DESCRIPTION
**Pull request by TheAndrey777**

### CODE REVIEW

**Comment by Twi5TeD** [comment]
you haven't added offline support? ive tried this in the past it wouldn't work as you cannot get offline player statistics

**Comment by TheAndrey777** [comment]
it worked for me. I passed offline player to PlaceholderAPI.setPlaceholders(player, "%playtime_time%"); and it worked. You can try. Before this changes when i pass offline player i was getting %playtime_time%

**Comment by TheAndrey777** [comment]
https://www.spigotmc.org/resources/placeholderapi.6245/update?update=229457

**Comment by Twi5TeD** [comment]
image

**Pull request closed without merging**
